FROM gliderlabs/alpine:3.1
MAINTAINER António Meireles <antonio.meireles@reformi.st>

# svelto ma non troppo
RUN apk-install bash coreutils findutils diffutils \
                procps grep sed curl ca-certificates

ENTRYPOINT ["/bin/bash"]
